# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a6faa6b88c8a82b1f9e9c2030e365e4be425a0c73a05dd91e8c5d6e17833e3be84bbc2cee152d239a746c0efceb7dcd36afa1194e2a6af1c9169f58a6a14ca78

test:
  secret_key_base: 5696419e21aa7f00a0d53f5933944a1578a0241d8815bd22960d259d0a05d28b6e43906f2d90166416eb5e29a9f4bb5fa6330f0da7b7c716d5491d48e82d3da1

# Do not keep production secrets in the repository,
# instead read values from the environment.
# Add the following environment variable to the App 
# "SECRET_KEY_BASE". Get the secret key with:
# "bundle exec rake secret"
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
